import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy — AnnaAi',
}

export default function PrivacyPage() {
  return (
    <>
      <h1>Privacy Policy</h1>
      <p className="text-sm text-muted">Last updated: April 17, 2026</p>

      <h2>1. Introduction</h2>
      <p>
        AnnaAi (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) respects your privacy. This
        Privacy Policy explains what data we collect, how we use it, and your
        rights regarding your personal information.
      </p>

      <h2>2. Data We Collect</h2>

      <h3>Account Data</h3>
      <p>
        When you create an account, we collect your email address, name, and
        organization details. Authentication is handled by Supabase.
      </p>

      <h3>Content Data</h3>
      <p>
        We store the content your brand provides during onboarding (website
        text, brand voice descriptions) and the content drafts generated by
        our AI agents. This data is stored in your organization workspace.
      </p>

      <h3>Integration Data</h3>
      <p>
        When you connect third-party platforms (WordPress, Google Analytics,
        Google Search Console), we store encrypted OAuth tokens and access
        credentials required to interact with those platforms on your behalf.
      </p>

      <h3>Usage Data</h3>
      <p>
        We collect logs of API requests, agent run history, and feature usage
        to maintain and improve the Service. This data includes IP addresses,
        request timestamps, and request paths.
      </p>

      <h2>3. How We Use Your Data</h2>
      <ul>
        <li>To provide and operate the Service (generating content, publishing, analytics).</li>
        <li>To personalise AI-generated content to match your brand voice.</li>
        <li>To send transactional emails (daily briefs, account notifications).</li>
        <li>To monitor and improve Service reliability and performance.</li>
        <li>To enforce our Terms of Service and prevent abuse.</li>
      </ul>

      <h2>4. Data Storage and Security</h2>
      <p>
        Your data is stored on Supabase (PostgreSQL) with row-level security
        enforced at the database level. OAuth tokens are encrypted using
        Fernet symmetric encryption. We use HTTPS for all data in transit.
      </p>

      <h2>5. Third-Party Services</h2>
      <p>We use the following third-party services to operate AnnaAi:</p>
      <ul>
        <li><strong>Supabase</strong> — database, authentication, and file storage.</li>
        <li><strong>Anthropic (Claude)</strong> — AI model for content generation.</li>
        <li><strong>Paystack</strong> — payment processing.</li>
        <li><strong>Resend</strong> — transactional email delivery.</li>
        <li><strong>Vercel</strong> — frontend hosting.</li>
        <li><strong>Render</strong> — backend hosting.</li>
      </ul>
      <p>
        Each of these services has their own privacy policy. We only share the
        minimum data necessary for each service to function.
      </p>

      <h2>6. Data Retention</h2>
      <p>
        We retain your data for as long as your account is active. When you
        delete your account, all associated data (organization, drafts, runs,
        brand memory, chat history, and integration credentials) is
        permanently deleted.
      </p>

      <h2>7. Your Rights</h2>
      <p>You have the right to:</p>
      <ul>
        <li><strong>Access</strong> your personal data via the Settings page and API.</li>
        <li><strong>Correct</strong> inaccurate data via the Settings page.</li>
        <li><strong>Delete</strong> your account and all associated data at any time.</li>
        <li><strong>Object</strong> to data processing by contacting us.</li>
        <li><strong>Export</strong> your data by contacting us at the address below.</li>
      </ul>

      <h2>8. Cookies</h2>
      <p>
        We use essential cookies only for authentication session management.
        We do not use advertising or tracking cookies.
      </p>

      <h2>9. Children</h2>
      <p>
        The Service is not directed at individuals under 18. We do not
        knowingly collect personal data from children.
      </p>

      <h2>10. Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. We will notify
        you of material changes via email or in-app notice.
      </p>

      <h2>11. Contact</h2>
      <p>
        For privacy-related questions or to exercise your rights, contact us
        at <a href="mailto:privacy@annaai.app">privacy@annaai.app</a>.
      </p>
    </>
  )
}
