import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — AnnaAi',
}

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="text-sm text-muted">Last updated: April 17, 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using AnnaAi (&quot;the Service&quot;), operated by AnnaAi
        (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;), you agree to be bound by these Terms of
        Service. If you do not agree, do not use the Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        AnnaAi is an autonomous AI marketing agent that researches, writes, and
        publishes content on behalf of your brand. The Service includes a web
        dashboard, AI-generated content drafts, automated publishing to
        connected platforms, and analytics.
      </p>

      <h2>3. Account Registration</h2>
      <p>
        You must provide accurate information when creating an account. You are
        responsible for maintaining the confidentiality of your credentials and
        for all activity under your account.
      </p>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service to generate spam, misleading, or harmful content.</li>
        <li>Attempt to circumvent rate limits, plan restrictions, or security controls.</li>
        <li>Reverse-engineer, scrape, or interfere with the Service infrastructure.</li>
        <li>Violate any applicable law or third-party rights.</li>
      </ul>

      <h2>5. Content Ownership</h2>
      <p>
        You retain ownership of all content generated through the Service for
        your brand. We do not claim intellectual property rights over your
        drafts or published content. We may use anonymised, aggregated data to
        improve the Service.
      </p>

      <h2>6. AI-Generated Content</h2>
      <p>
        Content produced by AnnaAi is generated by AI models. While we strive
        for accuracy and quality, you are responsible for reviewing all content
        before publication. We do not guarantee that AI-generated content is
        free from errors, bias, or inaccuracies.
      </p>

      <h2>7. Billing and Subscriptions</h2>
      <p>
        Paid plans are billed monthly via Paystack. You may cancel at any time;
        your access continues until the end of the billing period. Refunds are
        handled on a case-by-case basis.
      </p>

      <h2>8. Data and Privacy</h2>
      <p>
        Your use of the Service is also governed by our{' '}
        <a href="/privacy">Privacy Policy</a>. We take data protection
        seriously and process your data in accordance with applicable laws.
      </p>

      <h2>9. Service Availability</h2>
      <p>
        We aim for high availability but do not guarantee uninterrupted
        service. We may perform maintenance, updates, or changes that
        temporarily affect availability.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, AnnaAi shall not be liable for
        any indirect, incidental, or consequential damages arising from your
        use of the Service. Our total liability shall not exceed the fees paid
        by you in the 12 months preceding the claim.
      </p>

      <h2>11. Termination</h2>
      <p>
        We may suspend or terminate your account if you violate these Terms.
        You may delete your account at any time through the Settings page.
        Upon deletion, all your data will be permanently removed.
      </p>

      <h2>12. Changes to Terms</h2>
      <p>
        We may update these Terms from time to time. We will notify you of
        material changes via email or in-app notice. Continued use of the
        Service after changes constitutes acceptance.
      </p>

      <h2>13. Contact</h2>
      <p>
        For questions about these Terms, contact us at{' '}
        <a href="mailto:support@annaai.app">support@annaai.app</a>.
      </p>
    </>
  )
}
